[project]
name = "todo-fast"
version = "0.1.0"
description = "Simple todo API with FastAPI. "
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bcrypt>=4.2.1",
    "fastapi>=0.115.6",
    "pyjwt>=2.10.1",
    "python-dotenv>=1.0.1",
]
